export const validationLangs = {
  required: "Please fill in this field!",
  min: "Field must contain more than @min Character!",
  max: "Field must be less than @max Character!",
  min_max: "Field must be @min - @max Character!",
  phone: "Please enter valid mobile number!",
  url: "Please enter valid url!",
  uppercase: "Field must be at least 1 uppercase!",
  lowercase: "Field must be at least 1 lowercase!",
  numeric: "Field must be at least 1 numeric!",
  email: "Please enter valid email!",
  in: "Field must be one of @keywords",
  not_in: "Field can't one of @keywords",
  regex: "Please enter valid format",
  invalid_file_type: "Only allow extensions @extension",
  max_file_size: "Max file size @maxFileSize Mb",
};
