import { Command } from "commander";
import { usePdf } from "./use-pdf";
import { blueprint } from "./blueprint";
import { logger } from "../logger";
import fs from "fs";
import path from "path";
import { exec, execSync, spawn } from "child_process";

// =====================================>
// ## Command: use-pdf
// =====================================>
export const usePdfCommand = new Command("use-pdf")
  .description("Copy pdf.worker.min.mjs ke folder public/")
  .action(() => {
    usePdf();
  });

// =====================================>
// ## Command: blueprint
// =====================================>
export const blueprintCommand = new Command("blueprint")
  .description("Generate blueprint")
  .option("-o, --only <names...>", "Run only specific blueprints")
  .action(async (opts: { only?: string[] }) => {
    await blueprint({ only: opts.only });
    logger.info("Success run all blueprints!");
    process.exit(0);
  });

function postProcessBarrels(rootDir: string) {
  const componentsIndex = path.join(rootDir, "components", "index.ts");
  if (!fs.existsSync(componentsIndex)) {
    const defaultContent = `export * from "@skalfa/skalfa-component";\n\n/**\n * @file Automatically generated by barrelsby.\n */\n`;
    fs.writeFileSync(componentsIndex, defaultContent, "utf8");
    return;
  }

  let content = fs.readFileSync(componentsIndex, "utf8");

  // Find all export * from './relative/path'
  const exportStarRegex = /export\s+\*\s+from\s+['"](\.\/[^'"]+)['"]/g;
  let match;
  const localExports: string[] = [];
  while ((match = exportStarRegex.exec(content)) !== null) {
    localExports.push(match[1]);
  }

  if (localExports.length === 0) {
    if (!content.includes("@skalfa/skalfa-component")) {
      const defaultContent = `export * from "@skalfa/skalfa-component";\n\n` + content.trim() + "\n";
      fs.writeFileSync(componentsIndex, defaultContent, "utf8");
    }
    return;
  }

  const explicitExports: string[] = [];
  const componentsDir = path.join(rootDir, "components");

  for (const relPath of localExports) {
    const possiblePaths = [
      path.resolve(componentsDir, relPath + ".tsx"),
      path.resolve(componentsDir, relPath + ".ts"),
      path.resolve(componentsDir, relPath, "index.tsx"),
      path.resolve(componentsDir, relPath, "index.ts"),
    ];

    let filePath = "";
    for (const p of possiblePaths) {
      if (fs.existsSync(p)) {
        filePath = p;
        break;
      }
    }

    if (!filePath) continue;

    const fileContent = fs.readFileSync(filePath, "utf8");
    const symbolRegex = /export\s+(?:async\s+)?(const|let|var|function|class|type|interface)\s+(\w+)/g;
    let symbolMatch;
    const values: string[] = [];
    const types: string[] = [];
    while ((symbolMatch = symbolRegex.exec(fileContent)) !== null) {
      const keyword = symbolMatch[1];
      const name = symbolMatch[2];
      if (keyword === "type" || keyword === "interface") {
        types.push(name);
      } else {
        values.push(name);
      }
    }

    if (values.length > 0) {
      explicitExports.push(`export { ${values.join(", ")} } from "${relPath}";`);
    }
    if (types.length > 0) {
      explicitExports.push(`export type { ${types.join(", ")} } from "${relPath}";`);
    }
  }

  const newContent = [
    `export * from "@skalfa/skalfa-component";`,
    ``,
    content.trim(),
    ``,
    `// ==================================================>`,
    `// ## Explicit overrides to resolve export ambiguity`,
    `// ==================================================>`,
    ...explicitExports
  ].join("\n") + "\n";

  fs.writeFileSync(componentsIndex, newContent, "utf8");
}

// =====================================>
// ## Command: barrels (run once)
// =====================================>
export const barrelsCommand = new Command("barrels")
  .description("Generate barrels auto-imports using barrelsby")
  .action(() => {
    const rootDir = process.cwd();
    const configPath = path.join(rootDir, "barrels.json");

    if (!fs.existsSync(configPath)) {
      logger.error("barrels.json config file not found at project root");
      process.exit(1);
    }

    logger.info("Generating barrels...");
    try {
      execSync("npx barrelsby -c barrels.json", { cwd: rootDir, stdio: "inherit" });
      postProcessBarrels(rootDir);
      logger.info("Barrels successfully generated!");
      process.exit(0);
    } catch (err) {
      logger.error(`Failed to generate barrels: ${err}`);
      process.exit(1);
    }
  });

// =====================================>
// ## Command: watch:barrels (file watcher)
// =====================================>
export const watchBarrelsCommand = new Command("watch:barrels")
  .description("Watch directories and update barrels automatically on file changes")
  .action(async () => {
    const rootDir = process.cwd();
    const configPath = path.join(rootDir, "barrels.json");

    if (!fs.existsSync(configPath)) {
      logger.error("barrels.json config file not found at project root");
      process.exit(1);
    }

    let config: any = {};
    try {
      const configText = fs.readFileSync(configPath, "utf8");
      config = JSON.parse(configText);
    } catch (err) {
      logger.error(`Failed to parse barrels.json: ${err}`);
      process.exit(1);
    }

    const directories: string[] = Array.isArray(config.directory) ? config.directory : [config.directory];

    // Run barrels once at startup
    logger.info("Initializing barrels generation...");
    try {
      execSync("npx barrelsby -c barrels.json", { cwd: rootDir });
      postProcessBarrels(rootDir);
    } catch {}

    let debounceTimer: NodeJS.Timeout | null = null;
    const runBarrels = () => {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }
      debounceTimer = setTimeout(() => {
        exec("npx barrelsby -c barrels.json", { cwd: rootDir }, (error) => {
          if (error) {
            logger.error(`Failed to update barrels: ${error.message}`);
          } else {
            try {
              postProcessBarrels(rootDir);
              logger.info("Barrels updated successfully!");
            } catch (postErr: any) {
              logger.error(`Failed to post-process barrels: ${postErr.message}`);
            }
          }
        });
      }, 300);
    };

    directories.forEach((dir) => {
      const absoluteDir = path.join(rootDir, dir);

      if (!fs.existsSync(absoluteDir)) {
        logger.error(`Barrels error: ${absoluteDir} directory not found`);
        return;
      }

      fs.watch(absoluteDir, { recursive: true }, (_, filename) => {
        if (
          filename &&
          (filename.endsWith(".ts") || filename.endsWith(".tsx")) &&
          !filename.endsWith("index.ts") &&
          !filename.endsWith("index.tsx")
        ) {
          runBarrels();
        }
      });
    });

    logger.start("Barrels watcher running for: " + directories.join(", "));
  });

function getPackageManager(): string {
  const userAgent = process.env.npm_config_user_agent || "";
  if (userAgent.includes("yarn")) return "yarn";
  if (userAgent.includes("pnpm")) return "pnpm";
  if (userAgent.includes("bun")) return "bun";
  return "npm";
}

function executeCommand(commandLine: string): void {
  const child = spawn(commandLine, { stdio: "inherit", shell: true });
  child.on("exit", (code) => {
    process.exit(code || 0);
  });
}

import os from "os";

function getGlobalSkalfa(): string {
  try {
    const cmd = os.platform() === "win32" ? "where.exe skalfa" : "which skalfa";
    const paths = execSync(cmd, { stdio: "pipe" }).toString().trim().split(/\r?\n/);
    for (const p of paths) {
      const normalized = p.trim();
      if (normalized && !normalized.includes("node_modules") && !normalized.includes(process.cwd())) {
        return normalized;
      }
    }
  } catch {}
  return "skalfa";
}

function runGenerate(projectRoot: string, quiet = false): boolean {
  let scriptPath = path.join(projectRoot, "node_modules", "@skalfa", "skalfa-icon", "scripts", "generate.ts");
  if (!fs.existsSync(scriptPath)) {
    // Fallback for monorepo development
    scriptPath = path.resolve(projectRoot, "..", "skalfa-icon", "scripts", "generate.ts");
  }

  if (fs.existsSync(scriptPath)) {
    try {
      execSync(`bun run "${scriptPath}"${quiet ? " --quiet" : ""}`, { stdio: "inherit", cwd: projectRoot });
      return true;
    } catch (err: any) {
      logger.error("❌ Failed to execute icon generator script: " + err.message);
      return false;
    }
  } else {
    logger.error("❌ Error: @skalfa/skalfa-icon package not found. Make sure it is installed.");
    return false;
  }
}

export async function runBuildIcon(projectRoot: string, quiet = false): Promise<boolean> {
  if (!quiet) logger.info("🔍 Building custom SVG icons...");
  return runGenerate(projectRoot, quiet);
}

export async function startDevIcon(projectRoot: string, quiet = false): Promise<void> {
  const iconsDir = path.resolve(projectRoot, "icons");
  if (!fs.existsSync(iconsDir)) {
    if (!quiet) logger.info(`📁 Creating missing icons folder: ${iconsDir}`);
    fs.mkdirSync(iconsDir, { recursive: true });
  }

  if (quiet) {
    logger.info(`[START] Icon watcher running for: ${iconsDir}`);
  } else {
    logger.info("👀 Starting icon development watcher...");
    logger.info(`📺 Watching SVG files in: ${iconsDir}`);
  }

  runGenerate(projectRoot, quiet);

  let isThrottled = false;
  fs.watch(iconsDir, { recursive: true }, (eventType, filename) => {
    if (filename && filename.endsWith(".svg")) {
      if (isThrottled) return;
      isThrottled = true;
      setTimeout(() => {
        isThrottled = false;
      }, 300); // 300ms throttle

      logger.info(`\n⚡ Icon file change detected: ${filename} (${eventType})`);
      runGenerate(projectRoot, quiet);
    }
  });
}

export const iconCommand = new Command("icon")
  .description("Manage and compile custom SVG icons for @skalfa/skalfa-icon");

iconCommand
  .command("build")
  .description("Compile custom SVG icons once")
  .option("-q, --quiet", "Run in quiet mode")
  .action(async (options) => {
    const success = await runBuildIcon(process.cwd(), !!options.quiet);
    if (!success) process.exit(1);
    process.exit(0);
  });

iconCommand
  .command("dev")
  .description("Start icon development watcher")
  .option("-q, --quiet", "Run in quiet mode")
  .action(async (options) => {
    await startDevIcon(process.cwd(), !!options.quiet);
  });

export const devCommand = new Command("dev")
  .description("Start development server")
  .action(() => {
    const pm = getPackageManager();
    const globalSkalfa = getGlobalSkalfa();
    const escapedSkalfa = globalSkalfa.includes(" ") ? `\\"${globalSkalfa}\\"` : globalSkalfa;
    executeCommand(`concurrently --raw "${pm} run skalfa watch" "${pm} run skalfa watch:barrels" "${pm} run skalfa icon dev --quiet" "${escapedSkalfa} lang dev --quiet"`);
  });

export const watchCommand = new Command("watch")
  .description("Start dev watch process")
  .action(() => {
    const pm = getPackageManager();
    const port = process.env.NEXT_PUBLIC_APP_PORT || "3000";
    executeCommand(pm === "bun" ? `bun next dev -p ${port} --webpack` : `next dev -p ${port} --webpack`);
  });

export const buildCommand = new Command("build")
  .description("Build production bundle")
  .action(async () => {
    await runBuildIcon(process.cwd(), true);
    executeCommand("next build --webpack");
  });

export const startCommand = new Command("start")
  .description("Start production server")
  .action(() => {
    const port = process.env.NEXT_PUBLIC_APP_PORT || "3000";
    executeCommand(`next start -p ${port}`);
  });

export const testCommand = new Command("test")
  .description("Run typescript compiler check")
  .action(() => {
    const pm = getPackageManager();
    executeCommand(pm === "bun" ? "bun tsc --noEmit" : "tsc --noEmit");
  });

export const lintCommand = new Command("lint")
  .description("Run eslint check")
  .action(() => {
    const pm = getPackageManager();
    executeCommand(pm === "bun" ? "bunx eslint app/* components/* utils/* contexts/*" : "eslint app/* components/* utils/* contexts/*");
  });

export function runCli() {
  const program = new Command();
  program.name("skalfa").description("Skalfa-app CLI").version("1.0.0");

  program.addCommand(usePdfCommand);
  program.addCommand(blueprintCommand);
  program.addCommand(barrelsCommand);
  program.addCommand(watchBarrelsCommand);
  program.addCommand(devCommand);
  program.addCommand(watchCommand);
  program.addCommand(buildCommand);
  program.addCommand(startCommand);
  program.addCommand(testCommand);
  program.addCommand(lintCommand);
  program.addCommand(iconCommand);

  program.parse(process.argv);
}
